version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "81:80"
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure